version: "3"

services:
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/:/data/db

  redis: 
    image: redis:6.2.5
    command: redis-server --requirepass salar
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/:/data